import { BoardInput } from './BoardInput'
import type { BoardProps } from '../../types'

export function MultiplicationBoard({ question, current, completed, value, onChange, disabled }: BoardProps) {
  const partials = completed.filter((item) => item.kind === 'partial').map((item) => item.expected)
  const activeRow = current.meta?.row
  const carryStep = ['multiply-carry', 'multiply-carry-final'].includes(current.kind)
  return <div className="board multiplication-board"><div className="board-label">KALI PER KOLOM <span className="board-live">● simpan carry di atas</span></div><div className="multiplication-expression"><span>{question.a}</span><b>×</b><span>{question.b}</span></div><div className="mini-rule" /><div className="carry-strip">{carryStep ? <BoardInput value={value} onChange={onChange} disabled={disabled} placeholder="carry" /> : <span className="carry-guide">{current.kind === 'multiply-column' ? 'hitung kolom ini' : 'ikuti baris hasil'}</span>}</div><div className="partial-lines"><div><small>baris 1</small><strong>{partials[0] || '· · ·'}</strong></div>{question.b! >= 10 && <div className={activeRow === 1 ? 'active-row' : ''}><small>baris 2 digeser ←</small><strong>{partials[1] || '· · ·'}</strong></div>}{completed.some((item) => item.kind === 'partial-sum') && <div className="sum-result"><small>jumlahkan</small><strong>{completed.find((item) => item.kind === 'partial-sum')?.expected}</strong></div>}</div>{!carryStep && <div className="board-entry-row"><span>{current.kind === 'final' ? 'Hasil akhir' : current.kind === 'partial' || current.kind === 'partial-sum' ? 'Isi hasil baris' : 'Hasil kolom ini'}</span><BoardInput value={value} onChange={onChange} disabled={disabled} className={['final', 'partial', 'partial-sum'].includes(current.kind) ? 'wide-input' : ''} placeholder={current.kind === 'final' ? 'hasil' : '?'} /></div>}<div className="board-caption"><span className="caption-dot" /> Setiap baris dikerjakan dari kanan ke kiri</div></div>
}
